### ISSUE TITLE
cannot unmarshal bool into Go value of type string

### ISSUE THREAD

**Issue by reggi** [jfrazelle/weather#3]
I hate to be this person, but I found another bug.

```
thomas@workstation:jspm-npm$ weather -l "Manhattan Beach, CA"
Decoding the response from https://geocode.jessfraz.com/forecast failed: json: cannot unmarshal bool into Go value of type string
```

**Comment by jfrazelle** [comment]
I might have hit a rate limit I didn't really publicize this project
because of that in first place :P but if that's not the problem pull
requests welcome!

On Thursday, January 8, 2015, Thomas Reggi <notifications@github.com> wrote:

> I hate to be this person, but I found another bug.
>
> thomas@workstation:jspm-npm$ weather -l "Manhattan Beach, CA"
> Decoding the response from https://geocode.jessfraz.com/forecast failed: json: cannot unmarshal bool into Go value of type string
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/3>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by reggi** [comment]
Makes sense! An option to add your own forecast keys would work. Fee free to close.

**Comment by jfrazelle** [comment]
fixed
